# Generated by Django 4.2.7 on 2025-09-24 12:11

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.PositiveIntegerField(help_text='Номер трассы (1-140)', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(140)], verbose_name='№ трассы')),
                ('track_lane', models.PositiveIntegerField(help_text='Номер дорожки (1-35)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(35)], verbose_name='№ дорожки')),
                ('name', models.CharField(help_text='Название трассы', max_length=200, verbose_name='Название')),
                ('difficulty', models.CharField(choices=[('4', '4'), ('4-5', '4-5'), ('5', '5'), ('5+', '5+'), ('6A', '6A'), ('6A+', '6A+'), ('6B', '6B'), ('6B+', '6B+'), ('6C', '6C'), ('6C+', '6C+'), ('7A', '7A'), ('7A+', '7A+'), ('7B', '7B'), ('7B+', '7B+'), ('7C', '7C'), ('7C+', '7C+'), ('8A', '8A'), ('8A+', '8A+'), ('8B', '8B'), ('8B+', '8B+'), ('8C', '8C'), ('9A', '9A'), ('-', '-')], help_text='Уровень сложности трассы', max_length=10, verbose_name='Сложность')),
                ('color', models.CharField(help_text='Цвет трассы (например: красный, синий, зеленый)', max_length=50, verbose_name='Цвет')),
                ('author', models.CharField(help_text='Имя автора трассы', max_length=100, verbose_name='Автор трассы')),
                ('setup_date', models.CharField(help_text='Дата когда трасса была накручена (DD.MM.YYYY)', max_length=10, verbose_name='Дата накрутки')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание трассы', null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли трасса (не скручена)', verbose_name='Активна')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время создания записи в системе', verbose_name='Дата создания записи')),
            ],
            options={
                'verbose_name': 'Трасса',
                'verbose_name_plural': 'Трассы',
                'ordering': ['route_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('track_lane', 'route_number'), name='unique_lane_route'),
        ),
    ]
