# Generated by Django 4.2.7 on 2025-09-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='difficulty',
            field=models.CharField(choices=[('4', '4'), ('4-5', '4-5'), ('5', '5'), ('5+', '5+'), ('6a', '6a'), ('6a+', '6a+'), ('6b', '6b'), ('6b+', '6b+'), ('6c', '6c'), ('6c+', '6c+'), ('7a', '7a'), ('7a+', '7a+'), ('7b', '7b'), ('7b+', '7b+'), ('7c', '7c'), ('7c+', '7c+'), ('8a', '8a'), ('8a+', '8a+'), ('8b', '8b'), ('8b+', '8b+'), ('8c', '8c'), ('9a', '9a'), ('-', '-')], help_text='Уровень сложности трассы', max_length=10, verbose_name='Сложность'),
        ),
    ]
