# Generated by Django 4.2.7 on 2025-09-25 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_route_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Логин администратора', max_length=50, unique=True, verbose_name='Логин')),
                ('password_hash', models.CharField(help_text='Хешированный пароль', max_length=128, verbose_name='Хеш пароля')),
                ('full_name', models.CharField(help_text='Полное имя администратора', max_length=100, verbose_name='Полное имя')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли администратор', verbose_name='Активен')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата создания аккаунта', verbose_name='Дата создания')),
                ('last_login', models.DateTimeField(blank=True, help_text='Дата и время последнего входа', null=True, verbose_name='Последний вход')),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
                'ordering': ['username'],
            },
        ),
    ]
