# Generated by Django 4.2.7 on 2025-09-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_number',
            field=models.PositiveIntegerField(help_text='Номер трассы (автоматический)', unique=True, verbose_name='№ трассы'),
        ),
    ]
