# Generated by Django 4.2.7 on 2025-09-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_alter_route_route_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['track_lane', 'route_number'], 'verbose_name': 'Трасса', 'verbose_name_plural': 'Трассы'},
        ),
    ]
