# Generated by Django 4.2.7 on 2025-09-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_alter_route_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='route',
            name='unique_lane_route',
        ),
    ]
