# Generated by Django 4.2.7 on 2025-09-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_remove_route_unique_lane_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_number',
            field=models.PositiveIntegerField(help_text='Номер трассы (автоматический)', verbose_name='№ трассы'),
        ),
    ]
